# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20160922_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='Suscripcion',
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
    ]
