# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0002_auto_20160726_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='profesionales.Servicio')),
            ],
        ),
    ]
