# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20161006_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
