# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metodo_trabajo',
            field=models.CharField(blank=True, choices=[('a', 'Autónomo'), ('e', 'Empresa'), ('p', 'Particular')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(blank=True, choices=[('am', 'Amigo'), ('em', 'Email'), ('bu', 'Buscador'), ('fa', 'Facebook'), ('tw', 'Twitter'), ('in', 'Instagram'), ('mi', 'Milanuncios'), ('jo', 'JobToday'), ('ot', 'Otros')], max_length=2, null=True),
        ),
    ]
