# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20161108_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='donde',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='informacion_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metodo_contacto',
            field=models.CharField(blank=True, choices=[('1', 'Prefiero Llamar'), ('2', 'Prefiere que me llamen')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
