# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20161108_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(blank=True, max_length=5, null=True)),
                ('campo2', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuestionario_extra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.CuestionarioExtra'),
        ),
    ]
