# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20161108_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cuestionario_extra',
            new_name='cuestionario',
        ),
    ]
