# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('lugar_de_residencia', models.CharField(max_length=30)),
                ('radio_prestacion', models.IntegerField()),
                ('web', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100)),
                ('como', models.TextField()),
                ('que', models.TextField()),
                ('experiencia', models.TextField()),
                ('consejo', models.TextField(blank=True)),
                ('formacion', models.TextField(blank=True)),
                ('tipo_cliente', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('contacto_cliente', models.CharField(max_length=100)),
                ('recomendacion_cliente', models.TextField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='profesionales.Profesional')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicios',
            field=models.ManyToManyField(to='profesionales.Servicio'),
        ),
    ]
