# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='linked_in',
            new_name='linkedin',
        ),
    ]
