# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 11:16
from __future__ import unicode_literals

from django.db import migrations


def servicios_iniciales(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    Servicio.objects.create(nombre_servicio='Cuidado de niños')
    Servicio.objects.create(nombre_servicio='Monitor de deportes')
    Servicio.objects.create(nombre_servicio='Profesor particular')


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(servicios_iniciales),
    ]
