# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:45
from __future__ import unicode_literals

from django.db import migrations


def servicios_iniciales(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    Servicio.objects.create(nombre_servicio='Cuidado de niños')
    Servicio.objects.create(nombre_servicio='Deportes')
    Servicio.objects.create(nombre_servicio='Clases particulares')
    Servicio.objects.create(nombre_servicio='Salud y bienestar')
    Servicio.objects.create(nombre_servicio='Hogar y limpieza')
    Servicio.objects.create(nombre_servicio='Reparaciones y reformas')
    Servicio.objects.create(nombre_servicio='Servicios informáticos')


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(servicios_iniciales),

    ]
