# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_auto_20160726_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='lugar_de_residencia',
            new_name='area_servicio',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='servicios',
            new_name='servicio',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='como',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='consejo',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='formacion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='radio_prestacion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='web',
        ),
    ]
