# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_auto_20161004_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['categoria', 'nombre_servicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
