# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_auto_20161006_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_alta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
