# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_auto_20160728_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='que',
            field=models.TextField(blank=True, null=True),
        ),
    ]
