# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 07:06
from __future__ import unicode_literals

from django.db import migrations


def actualizar_servicios(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    s1 = Servicio.objects.get(nombre_servicio='Profesor particular')
    s1.nombre_servicio = 'Clases particulares'
    s1.save()
    s2 = Servicio.objects.get(nombre_servicio='Monitor de deportes')
    s2.nombre_servicio = 'Deportes'
    s2.save()


def nuevos_servicios(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    Servicio.objects.create(nombre_servicio='Salud y bienestar')
    Servicio.objects.create(nombre_servicio='Hogar y limpieza')


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_auto_20160729_1311'),
    ]

    operations = [
        migrations.RunPython(actualizar_servicios),
        migrations.RunPython(nuevos_servicios),
    ]
