# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 07:20
from __future__ import unicode_literals

from django.db import migrations


def nuevos_servicios(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    Servicio.objects.create(nombre_servicio='Reparaciones y reformas')
    Servicio.objects.create(nombre_servicio='Servicios informáticos')


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_auto_20160907_0706'),
    ]

    operations = [
        migrations.RunPython(nuevos_servicios),
    ]
