# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_auto_20161018_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
    ]
