# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_auto_20161018_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
