# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0007_profesional_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='formacion_relacionada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='metodo_trabajo',
            field=models.CharField(blank=True, choices=[('a', 'Autónomo'), ('e', 'Empresa'), ('p', 'Particular')], max_length=1),
        ),
        migrations.AddField(
            model_name='profesional',
            name='opiniones_clientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
