# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0007_auto_20160907_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='profesional',
        ),
        migrations.DeleteModel(
            name='Trabajo',
        ),
    ]
