# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0008_auto_20161101_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='codigo_actualizacion',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
