# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0009_profesional_codigo_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='metodo_trabajo',
            field=models.CharField(blank=True, choices=[('a', 'Autónomo'), ('e', 'Empresa'), ('p', 'Particular')], max_length=1, null=True),
        ),
    ]
