# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:56
from __future__ import unicode_literals

from django.db import migrations


def actualizar_servicios(apps, schema_editor):
    Servicio = apps.get_model("profesionales", "Servicio")
    Categoria = apps.get_model("profesionales", "Categoria")

    clases_particulares = Categoria.objects.get(nombre_categoria='Clases particulares')
    Servicio.objects.create(categoria=clases_particulares, nombre_servicio='Inglés (nativo)')
    Servicio.objects.create(categoria=clases_particulares, nombre_servicio='Francés (nativo)')
    Servicio.objects.filter(categoria=clases_particulares, nombre_servicio='Mindfullness').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0010_auto_20161103_1915'),
    ]

    operations = [
        migrations.RunPython(actualizar_servicios),
    ]
