# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0011_auto_20161107_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='origen',
            field=models.CharField(blank=True, choices=[('am', 'Amigo'), ('em', 'Email'), ('bu', 'Buscador'), ('fa', 'Facebook'), ('tw', 'Twitter'), ('in', 'Instagram'), ('mi', 'Milanuncios'), ('jo', 'JobToday'), ('ot', 'Otros')], max_length=2, null=True),
        ),
    ]
