# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:41
from __future__ import unicode_literals

from django.db import migrations


def actualizar_servicios(apps, schema_editor):
    Categoria = apps.get_model("profesionales", "Categoria")

    salud_y_bienestar = Categoria.objects.get(nombre_categoria='Salud y bienestar')
    salud_y_bienestar.preguntas_especificas = '1. ¿Cuántas sesiones estimas que necesitas?\n\n' \
                                              '2. ¿Cuándo quieres empezar? Fecha aproximada. \n\n' \
                                              '3. ¿En qué franja horaria?\n\n'

    salud_y_bienestar.save()

    cuidado_de_personas = Categoria.objects.get(nombre_categoria='Cuidado de personas')
    cuidado_de_personas.preguntas_especificas = '1. En caso de niños: edad y número de niños.\n\n' \
                                                '2. En caso de ancianos: estado de salud\n\n' \
                                                '3. ¿Se trata de un servicio puntual o recurrente? ¿Cuántas semanas?\n\n' \
                                                '4. ¿Cuántas horas a la semana estimas que necesitarás contratar?\n\n' \
                                                '5. ¿Cuándo quieres empezar? Fecha aproximada.\n\n' \
                                                '6. ¿En qué franja horaria?\n\n'

    cuidado_de_personas.save()

    clases_particulares = Categoria.objects.get(nombre_categoria='Clases particulares')
    clases_particulares.preguntas_especificas = '1. En caso de inglés: nativo o no necesariamente.\n\n' \
                                                '2. ¿Alguna formación de preferencia del profesor?\n\n' \
                                                '3. Nivel del alumno\n\n' \
                                                '4. Objetivo perseguido con las clases.\n\n' \
                                                '5. ¿Se trata de un servicio puntual o recurrente? ¿Cuántas semanas?\n\n' \
                                                '6. ¿Cuántas horas a la semana estimas que necesitarás?\n\n' \
                                                '7. ¿Cuándo quieres empezar? Fecha aproximada.\n\n' \
                                                '8. ¿En qué franja horaria?\n\n'

    clases_particulares.save()

    deporte = Categoria.objects.get(nombre_categoria='Deportes')
    deporte.preguntas_especificas = '1. ¿Alguna formación de preferencia del profesor?\n\n' \
                                    '2. Nivel del alumno\n\n' \
                                    '3. Objetivo perseguido con las clases.\n\n' \
                                    '4. ¿Cuántas semanas?\n\n' \
                                    '5. ¿Se trata de un servicio puntual o recurrente?\n\n' \
                                    '6. ¿Cuántas horas a la semana estimas que necesitarás contratar?\n\n' \
                                    '7. ¿Cuándo quieres empezar? Fecha aproximada.\n\n' \
                                    '8. ¿En qué franja horaria?\n\n'

    deporte.save()

    hogar_y_limpieza = Categoria.objects.get(nombre_categoria='Hogar y limpieza')
    hogar_y_limpieza.preguntas_especificas = '1. ¿Quién aporta los productos de limpieza o jardinería?\n\n' \
                                             '2. ¿Se trata de un servicio puntual o recurrente? Cuántas semanas?\n\n' \
                                             '3. ¿Cuántas horas a la semana estimas que necesitarás contratar?\n\n' \
                                             '4. ¿Cuándo quieres empezar? Fecha aproximada.\n\n' \
                                             '5. ¿En qué franja horaria?\n\n'
    hogar_y_limpieza.save()

    servicios_informaticos = Categoria.objects.get(nombre_categoria='Servicios informáticos')
    servicios_informaticos.preguntas_especificas = '1. ¿Cuándo necesitas el trabajo terminado? Fecha aproximada.\n\n'

    servicios_informaticos.save()

    reparaciones_y_reformas = Categoria.objects.get(nombre_categoria='Reparaciones y reformas')
    reparaciones_y_reformas.preguntas_especificas = '1. Descríbenos los trabajos que quieres realizar.\n\n' \
                                                    '2. ¿Cuándo necesitas el trabajo terminado? Fecha aproximada.\n\n' \
                                                    '3. ¿Te gustaría pagar por horas o por trabajo terminado?\n\n'
    reparaciones_y_reformas.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0013_categoria_preguntas_especificas'),
    ]

    operations = [
        migrations.RunPython(actualizar_servicios),
    ]
